name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/template-build.yml
    with:
      release: true
      preview: false
    secrets: inherit
  
  release:
    runs-on: ubuntu-latest
    permissions:
      pages: write 
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Release to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
