name: ReleaseTest

on:
  workflow_dispatch:
    inputs:
      deployenv:
        description: "github pages env"
        default: "github-pages"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Node.js 18
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18

      # - name: Install dependencies
      #   run: |
      #     npm install -g yarn
      #     yarn install --frozen-lockfile

      # - name: Ignore OpenAPI
      #   run: |
      #     ./scripts/ignore-openapi

      # - name: Build
      #   env:
      #     NODE_OPTIONS: "--max_old_space_size=7168"
      #   run: |
      #     yarn gen-api-docs
      #     yarn build

      - name: test
        run: |
          mkdir -p "build/${{ inputs.deployenv }}"
          ls -al build
          echo "Hello, World! (${{ inputs.deployenv }})" > "build/${{ inputs.deployenv }}/index.html"
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build/${{ inputs.deployenv }}"
          
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    needs: build
    environment:
      name: ${{ inputs.deployenv }}
      url: "${{ steps.deployment.outputs.page_url }}${{ inputs.deployenv }}"
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4