on:
  workflow_call:
    inputs:
      production:
        required: true
        type: boolean


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: "Read some Secrets"
        uses: rancher-eio/read-vault-secrets@main
        if: ${{ inputs.production != true }}
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/netlify-auth-token/credentials token | NETLIFY_AUTH_TOKEN ;
            secret/data/github/repo/${{ github.repository }}/netlify-site-id/credentials token | NETLIFY_SITE_ID 

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile

      - name: Ignore OpenAPI
        run: |
          ./scripts/ignore-openapi

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=7168"
        run: |
          yarn gen-api-docs
          yarn build
      
      - name: Deploy to Netlify
        id: netlify
        if: ${{ inputs.production != true }}
        uses: nwtgck/actions-netlify@v3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: build
          production-deploy: false
          deploy-message: Deploy from ${{ github.event.pull_request.title }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          enable-commit-status: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}

      - name: Set outputs
        id: vars
        if: ${{ inputs.production == true }}
        run: | 
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "username=$(git log -1 --pretty=format:'%an')" >> $GITHUB_OUTPUT
          echo "email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_OUTPUT

      - name: Deploy to gh-pages branch
        if: ${{ inputs.production == true }}
        run: |
          npm install -g gh-pages
          GITHUB_REPO_WITH_TOKEN=$(echo ${GITHUB_REPO_LINK} | sed "s/\/\//\/\/git:${GITHUB_TOKEN}@/g")
          gh-pages -d build \
                    -o origin \
                    -m "deploy: ${COMMIT}" \
                    -u "${AUTHOR_USER} <${AUTHOR_EMAIL}>" \
                    -r ${GITHUB_REPO_WITH_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTHOR_USER: ${{ steps.vars.outputs.username }}
          AUTHOR_EMAIL: ${{ steps.vars.outputs.email }}
          COMMIT: ${{ steps.vars.outputs.sha_short }}
          GITHUB_REPO_LINK: "${{ github.server_url }}/${{ github.repository }}.git"
