on:
  workflow_call:
    inputs:
      production:
        required: true
        type: boolean


jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # - name: Install dependencies
      #   run: |
      #     npm install -g yarn
      #     yarn install --frozen-lockfile

      # - name: Ignore OpenAPI
      #   run: |
      #     ./scripts/ignore-openapi

      - name: Build
        env:
          NODE_OPTIONS: "--max_old_space_size=7168"
        run: |
          mkdir build
          echo "ai" > build/index.htm
          # yarn gen-api-docs
          # yarn build
      
      - name: Deploy to Netlify
        id: netlify
        if: ${{ inputs.production != true }}
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: build
          production-deploy: true
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Find the comment
        if: ${{ inputs.production != true }}
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Netlify Preview Deployment Information

      - name: Create or update comment
        if: ${{ inputs.production != true }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Netlify Preview Deployment Information
            - Preview URL: ${{ steps.netlify.outputs.deploy-url }}
          edit-mode: replace
      
      - name: Upload artifact
        if: ${{ inputs.production == true }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
