name: Testing

on: 
  workflow_dispatch:
  push:

jobs:
  readvault:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: test
      run:
        echo "test"q
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}