name: Testing

on: 
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'pull_request_number'
        required: true
        type: number
      pull_request_title:
        description: 'pull_request_title'
        type: string
        required: true
  pull_request:

jobs:
  readvault:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: build
      run:
        mkdir -p build
        echo "Hello, World!" > build/index.html

    - name: Deploy to Netlify
      id: netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        publish-dir: build
        production-deploy: false
        deploy-message: Deploy from ${{ github.event.pull_request.title }}
        enable-pull-request-comment: true
        enable-commit-comment: false
        enable-commit-status: false
        enable-github-deployment: false
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}